### ISSUE TITLE
Response is undefined when using enterprise endpoint

### ISSUE THREAD

**Issue by Zucovsky** [DrKain/audd.io#1]
Hi, when I use enterprise, result is undefined
![20210412_222345](https://user-images.githubusercontent.com/53387053/114457494-638a8700-9bde-11eb-99ec-d0e73f89270d.jpg)

**Comment by DrKain** [comment]
Looks like the enterprise result has a different response structure than the free api. I'll look into it, thanks for reporting

**Comment by DrKain** [comment]
I ended up purchasing an enterprise key so I could test and fix this. It should now be resolved. Please check the documentation for the new way to handle Enterprise accounts.  
If you have any more problems please feel free to open another issue.  
Thanks.
